### ISSUE TITLE
ჩონჩხი პროექტის შექმნა და რეპოში დაკომიტება

### ISSUE THREAD

**Issue by jibla** [dato-Qobuladze/FreeUni-Swift-2015-Final-Project----MovieChallenge#1]
ეს თასქი დასრულებულად ჩაითვლება მაშინ, როცა:
- შექმნილია ცარიელი პროექტი XCode-ში
- ტარგეთს მითითებული აქვს, რომ აპლიკაცია მუშაობს iPhone-ზეც და iPad-ზეც ყველა ორიენტაციაზე.
- იბილდება უპრობლემოდ
- აქ შექმნილია develop ბრენჩი
- სორსი დაკომიტებულია develop ბრენჩში
- კოდი დაკლონილი აქვს პროექტის ყველა მონაწილეს, თავიანნთან გაბილდული აქვთ და ყველას დაკომიტებული აქვს სიმბოლურად, რომ გამართულად მუშაობს სინქრონიზაცია.

პ.ს. git-თან სამუშაოდ გამოიყენეთ Xcode-ში ჩაშენებული კლიენტი და ხელით არ აკომიტოთ (ის ავოტმატურად მხოლოდ საჭირო ფაილებს აკომიტებს).

**Comment by jibla** [comment]
@toka16 @GROX13 @maghriany @dato-Qobuladze

**Comment by toka16** [comment]
შევქმენი ახალი ბრენჩი და დავამატე ცარიელი tab view project, რომელიც არის უნივერსალური(iPhone, iPad) და ასაპორტებს ყველა ორიენტაციას upside down-ის გარდა(არ ვიცი ესეც უნდა დავამატოთ თუ არა :/ ).
ამ issue-ს დასასრულებლად საჭიროა მხოლოდ ყველამ დაკლონოს ეს ბრენჩი და გაბილდონ @dato-Qobuladze @maghriany @GROX13
