### ISSUE TITLE
აპლიკაციის სქრინები

### ISSUE THREAD

**Issue by jibla** [dato-Qobuladze/FreeUni-Swift-2015-Final-Project----MovieChallenge#2]
Wiki-ში გვერდის შექმნა სადაც ჩამოწერილი იქნება რა სქრინები აქვს აპლიკაციას და მიახლოებით მოკაპები აიტვირთება ხოლმე.

ეს თასქი დასრულებულია, როცა:
- ვიკიში შექმნილია სპეციალური გვერდი ამისთვის
- ჩამოწერილია ყველა სქრინი (დაახლოებით ცხადია, რაც ახლა ვიცით და შემდეგ დაემატება) რაც აპლიკაციაში იქნება

გვერდს რო გააკეთებთ კომენტარში დალინკეთ.

**Comment by jibla** [comment]
@toka16  @GROX13  @maghriany  @dato-Qobuladze

**Comment by GROX13** [comment]
https://github.com/dato-Qobuladze/FreeUni-Swift-2015-Final-Project----MovieChallenge/wiki/Screens
