### ISSUE TITLE
რეგისტრაციის სქრინი

### ISSUE THREAD

**Issue by jibla** [dato-Qobuladze/FreeUni-Swift-2015-Final-Project----MovieChallenge#5]
- პაროლის textfield-ების ტიპები არის შესაცვლელი
- იმეილის ჩაწერისას, სტანდარტულისგან განსხვავებული განლაგების კლავიატურა უნდა ჩნდებოდეს (@ სიმბოლოიანი)

![iphone_5s_-_iphone_5s___ios_9_1__13b137_](https://cloud.githubusercontent.com/assets/475343/12174690/a7b4144e-b577-11e5-86a1-fde9b2cc68f2.png)

**Comment by GROX13** [comment]
შეცვლილია ეგენი ასატვირთია უბრალოდ.

**Comment by jibla** [comment]
როცა დააკომიტებთ თიქეთის ნომერი მიუთითეთ კომიტის მესიჯში.
მაგალითად ასე: "change password textfields' types and keyboard type for email. refs #5" ავტომატურად ამ იშუზე დაილინკება და პირიქით კომიტში ეს იშუ დაილინკება.
